version: '3.7'

services:
  shopware5-web:
    networks:
      default:
        aliases:
          - shopware5.dev.localhost
    volumes:
      - $HOME:$HOME
    ports:
      - 80:80
  shopware5-db:
    ports:
      - 3306:3306

#networks:
  #default:
    #external:
      #name: dev-proxy
